# Reference: https://github.com/libjxl/libjxl/blob/main/.github/workflows/release.yaml

FROM ubuntu:22.04

ARG LIBJXL_TAG=v0.11.1

ARG BUILD_JOBS
ENV DEBIAN_FRONTEND=noninteractive

COPY ./misc/build_scripts/linux/sources.list /etc/apt/sources.list
RUN apt update && apt install -y \
    git \
    clang \
    cmake \
    libbrotli-dev \
    libgdk-pixbuf2.0-dev \
    libgif-dev \
    libgtest-dev \
    libgtk2.0-dev  \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    ninja-build \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
RUN git clone -b ${LIBJXL_TAG} --depth 1 https://github.com/libjxl/libjxl.git libjxl
WORKDIR /src/libjxl/
RUN ./deps.sh
RUN TARGETS="-j ${BUILD_JOBS} all" \
    ./ci.sh release \
    -DJPEGXL_STATIC=ON \
    -DBUILD_TESTING=OFF \
    -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF \
    -DJPEGXL_ENABLE_VIEWERS=OFF \
    -DJPEGXL_ENABLE_PLUGINS=OFF \
    -DJPEGXL_ENABLE_OPENEXR=OFF \
    -DJPEGXL_ENABLE_DEVTOOLS=OFF \
    -DJPEGXL_ENABLE_DOXYGEN=OFF

WORKDIR /src/libjxl/build/tools/
RUN mkdir /src/bin/ && \
    cp cjxl djxl jxlinfo cjpegli /src/bin/
WORKDIR /src/bin/
CMD ["/bin/bash"]
