FROM ubuntu:22.04

ARG LIBJPEG_TURBO_TAG="3.2.0"

ARG BUILD_JOBS
ENV DEBIAN_FRONTEND=noninteractive

COPY ./misc/build_scripts/linux/sources.list /etc/apt/sources.list
RUN apt update && apt install -y \
    git \
    cmake \
    nasm \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
RUN git clone -b "$LIBJPEG_TURBO_TAG" --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo.git libjpeg-turbo
WORKDIR /src/libjpeg-turbo
RUN mkdir build && cd ./build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_STATIC=TRUE \
        ..
WORKDIR /src/libjpeg-turbo/build
RUN make -j${BUILD_JOBS}
RUN mkdir /src/bin && \
    cp jpegtran-static /src/bin/jpegtran
WORKDIR /src/bin
CMD ["/bin/bash"]
