FROM ubuntu:22.04

ARG IMAGEMAGICK_TAG="7.1.2-29"
ARG LIBHEIF_TAG="v1.23.1"
ARG LIBJXL_VERSION="0.12.0"
ARG BUILD_JOBS

ENV DEBIAN_FRONTEND=noninteractive

# Install deps
COPY ./misc/build_scripts/linux/sources.list /etc/apt/sources.list
RUN apt update && apt install -y \
    git \
    build-essential \
    autoconf \
    libtool \
    pkg-config \
    patchelf \
    pax-utils \
    nasm \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    libwebp-dev \
    libzstd-dev \
    libbz2-dev \
    liblzma-dev \
    libopenjp2-7-dev \
    wget \
    cmake \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global http.version HTTP/1.1

# Install libjxl (unavailable in Ubuntu 22.04)
WORKDIR /src
RUN apt update && apt install -y \
    clang \
    libbrotli-dev \
    libgif-dev \
    ninja-build \
    pkg-config \
    python3 \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 -b "v${LIBJXL_VERSION}" https://github.com/libjxl/libjxl.git libjxl
WORKDIR /src/libjxl
SHELL ["/bin/bash", "-c"]
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ./deps.sh
WORKDIR /src/libjxl/build
RUN cmake -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DJPEGXL_ENABLE_BENCHMARK=OFF \
    -DJPEGXL_ENABLE_PLUGINS=OFF \
    -DJPEGXL_ENABLE_MANPAGES=OFF \
    -DJPEGXL_FORCE_SYSTEM_BROTLI=ON \
    -DJPEGXL_FORCE_SYSTEM_GTEST=ON \
    -DJPEGXL_ENABLE_TOOLS=OFF \
    -DJPEGXL_ENABLE_OPENEXR=OFF \
    -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF \
    -DJPEGXL_ENABLE_TCMALLOC=OFF \
    -DJPEGXL_ENABLE_VIEWERS=OFF \
    -DJPEGXL_ENABLE_DEVTOOLS=OFF \
    ..
RUN cmake --build . --parallel ${BUILD_JOBS}
RUN make install

# Compile libheif without proprietary standards (like HEVC) to avoid licensing issues.
# This was very tricky to get working. Expect things to break. `magick -list format` can be wrong. Use `ldd`, and look for `libaom` when debugging.
RUN apt update && apt install -y \
    libaom-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone --depth 1 -b "${LIBHEIF_TAG}" https://github.com/strukturag/libheif.git
WORKDIR /src/libheif/build
# Do not specify the following. Otherwise ImageMagick will refuse to decode AVIF.
# -DWITH_AOM_ENCODER=ON \
# -DWITH_AOM_ENCODER_PLUGIN=ON \
# -DWITH_AOM_DECODER=ON \
# -DWITH_AOM_DECODER_PLUGIN=ON \
RUN cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_KVAZAAR=OFF \
    -DWITH_KVAZAAR_PLUGIN=OFF \
    -DWITH_LIBDE265=OFF \
    -DWITH_LIBDE265_PLUGIN=OFF \
    -DWITH_UVG266=OFF \
    -DWITH_UVG266_PLUGIN=OFF \
    -DWITH_VVDEC=OFF \
    -DWITH_VVDEC_PLUGIN=OFF \
    -DWITH_VVENC=OFF \
    -DWITH_VVENC_PLUGIN=OFF \
    -DWITH_X265=OFF \
    -DWITH_X265_PLUGIN=OFF \
    -DWITH_OPENJPH_ENCODER=OFF \
    -DWITH_OpenH264_DECODER=OFF \
    -DWITH_OpenH264_DECODER_PLUGIN=OFF \
    -DWITH_DAV1D=OFF \
    -DWITH_DAV1D_PLUGIN=OFF \
    -DWITH_EXAMPLES=OFF \
    -DWITH_FFMPEG_DECODER=OFF \
    -DWITH_FFMPEG_DECODER_PLUGIN=OFF \
    -DWITH_RAV1E=OFF \
    -DWITH_RAV1E_PLUGIN=OFF \
    -DWITH_SvtEnc=OFF \
    -DWITH_SvtEnc_PLUGIN=OFF \
    ..
RUN cmake --build . --parallel ${BUILD_JOBS}
RUN cmake --install .

# Build
WORKDIR /src
RUN git clone --depth 1 -b "${IMAGEMAGICK_TAG}" https://github.com/ImageMagick/ImageMagick.git ImageMagick
WORKDIR /src/ImageMagick
RUN ./configure \
    --enable-static \
    --disable-shared \
    --enable-hdri \
    --with-quantum-depth=16 \
    --with-modules \
    --without-perl \
    --without-magick-plus-plus \
    --with-png \
    --with-jpeg \
    --with-tiff \
    --with-webp \
    --with-jxl \
    --with-zstd \
    --with-bzlib \
    --with-lzma \
    --with-heic \
    --with-openjp2 \
    --without-raw \
    --disable-opencl \
    --without-wmf \
    --without-uhdr \
    --without-djvu \
    --without-openexr \
    --without-raqm \
    --without-jbig
RUN make -j${BUILD_JOBS}
WORKDIR /src/bin
RUN cp /src/ImageMagick/utilities/magick /src/bin/ && \
    mkdir /src/bin/lib

# Bundle
RUN <<EOT bash
    set -eux

    should_bundle() {
        local lib_name="\$(basename "\${1}")"
        local excluded_libraries=(
            "ld-linux-x86-64.so.2"
            "libc.so.6"
            "libgomp.so.1"
            "libm.so.6"
        )
        local pattern="^(\$(IFS="|"; echo "\${excluded_libraries[*]}"))"

        if [[ "\${lib_name}" =~ \${pattern} ]]; then
            echo "Skipping bundling \$lib_name"
            return 1
        fi

        echo "Bundling \$lib_name"
        return 0
    }
    mkdir -p lib

    for lib in \$(lddtree magick | grep "=>" | awk '{print \$3}' | grep "^/"); do
        if [[ -f "\${lib}" ]] && should_bundle "\${lib}"; then
            cp "\${lib}" ./lib/
            lib_name="\$(basename "\${lib}")"
            patchelf --set-rpath '\$ORIGIN' "./lib/\${lib_name}"
        fi
    done

    patchelf --set-rpath '\$ORIGIN/lib' ./magick
EOT

# Finish
CMD ["/bin/bash"]
