FROM ubuntu:22.04

# Git tags
ARG LIBAVIF_TAG=v1.4.2
ARG AOM_AV1_TAG=v3.14.1
ARG SVT_AV1_PSY_TAG=v3.0.2

ARG BUILD_JOBS
ENV DEBIAN_FRONTEND=noninteractive

COPY ./misc/build_scripts/linux/sources.list /etc/apt/sources.list
RUN apt update && apt install -y \
    libstdc++-12-dev \
    ninja-build \
    cmake \
    nasm \
    git \
    pkg-config \
    build-essential \
    libjpeg-turbo8-dev \
    && rm -rf /var/lib/apt/lists/*
# libjpeg-turbo8-dev needed for libyuv

WORKDIR /src
RUN git clone -b ${LIBAVIF_TAG} --depth 1 https://aomedia.googlesource.com/libavif.git libavif

WORKDIR /src/libavif/ext
RUN sed -i -E "s/v[0-9]+\.[0-9]+\.[0-9]+/${AOM_AV1_TAG}/" aom.cmd && \
    sed -i -E "s#https://gitlab.com/AOMediaCodec/SVT-AV1\.git#https://github.com/psy-ex/svt-av1-psy.git SVT-AV1#" svt.sh && \
    sed -i -E "s/v[0-9]+\.[0-9]+\.[0-9]+/${SVT_AV1_PSY_TAG}/" svt.sh && \
    sed -i -E "s/--parallel/--parallel ${BUILD_JOBS}/" aom.cmd && \
    sed -i -E "s#./build.sh#./build.sh jobs=${BUILD_JOBS}#" svt.sh

RUN chmod +x libyuv.cmd libsharpyuv.cmd libjpeg.cmd zlibpng.cmd svt.sh aom.cmd

RUN ./libyuv.cmd && \
    ./libsharpyuv.cmd && \
    ./libjpeg.cmd && \
    ./zlibpng.cmd && \
    ./svt.sh && \
    ./aom.cmd

WORKDIR /src/libavif/build
RUN cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=0 \
    -DAVIF_BUILD_APPS=1 \
    -DAVIF_LIBYUV=LOCAL \
    -DAVIF_LIBSHARPYUV=LOCAL \
    -DAVIF_JPEG=LOCAL \
    -DAVIF_ZLIBPNG=LOCAL \
    -DAVIF_CODEC_SVT=LOCAL \
    -DAVIF_CODEC_AOM=LOCAL \
    .. && \
    cmake --build . --parallel ${BUILD_JOBS}
WORKDIR /src/bin/
RUN cp /src/libavif/build/avifenc /src/bin/ && \
    cp /src/libavif/build/avifdec /src/bin/

CMD ["/bin/bash"]
