# Using oldest maintained version for best GLIBC compatibility.
FROM ubuntu:22.04

ARG RUN_TESTS=True

ENV DEBIAN_FRONTEND=noninteractive
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

COPY ./misc/build_scripts/linux/sources.list /etc/apt/sources.list
RUN apt update && apt install -y \
    git \
    make \
    curl \
    squashfs-tools \
    libfuse2 \
    file \
    p7zip-full \
    xvfb \
    '^libxcb.*-dev' \
    libfontconfig1-dev \
    libfreetype6-dev \
    libx11-dev \
    libx11-xcb-dev \
    libxext-dev \
    libxfixes-dev \
    libglu1-mesa-dev \
    libxrender-dev \
    libxi-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    wget \
    build-essential \
    libreadline-dev \
    libncursesw5-dev \
    libssl-dev \
    libsqlite3-dev \
    tk-dev \
    libgdbm-dev \
    libc6-dev \
    libbz2-dev \
    libffi-dev \
    zlib1g-dev \
    liblzma-dev \
    libdbus-1-3 \
    libpulse-dev \
    libegl1 \
    libpipewire-0.3-0 \
    exiftool \
    xdg-desktop-portal-gtk \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global http.version HTTP/1.1

# Install Python
RUN curl -fsSL https://pyenv.run | bash
RUN pyenv install 3.13 && \
    pyenv global 3.13

# Copy project files
WORKDIR /build
COPY assets /build/assets
COPY core /build/core
COPY data /build/data
COPY ui /build/ui
COPY bin /build/bin
COPY misc /build/misc
COPY tests /build/tests
COPY LICENSE* main.py requirements* test.py test_convert.py build.py /build/
RUN find /build/ -type d -name "__pycache__" -exec rm -rf {} +

# Run unit tests
RUN if [ "${RUN_TESTS}" = "True" ]; then \
        python -m venv /build/env_dev && \
        . /build/env_dev/bin/activate && \
        pip install -r /build/requirements.txt -r /build/requirements_test.txt && \
        xvfb-run -a python test.py && \
        xvfb-run -a python test_convert.py; \
    fi

# Setup virtual environment
RUN python -m venv /build/env_build && \
    . /build/env_build/bin/activate && \
    pip install -r /build/requirements.txt

# Setup PyInstaller
RUN cd /build && \
    ./misc/build_scripts/linux/pyinstaller.sh

# Build
RUN mkdir -p /export
RUN . /build/env_build/bin/activate && \
    xvfb-run -a python build.py -b sh -u && \
    cp /build/dist/*.7z /export && \
    mv /build/dist/*.json /export
RUN . /build/env_build/bin/activate && \
    xvfb-run -a python build.py -b appimage-skip-packing && \
    ./misc/appimagetool --appimage-extract && \
    BUILD_NAME=$(cat /build/dist/build_name.txt) && \
    ./squashfs-root/AppRun ./dist/AppDir ./dist/${BUILD_NAME} && \
    cp /build/dist/*.AppImage /export

CMD ["/bin/bash"]
