name: Feature Request
description: Suggest improvements
body:
  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description
      description: Write a brief description of a feature or an improvement you would like to see.
    validations:
      required: true
    
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: |
        Describe how this feature is intended to work conceptually.

        For a simple request, like a library update, you can keep it brief. For a new feature, describe thoroughly how it works.
        
        **New features with unclear descriptions will not be considered!**
    validations:
      required: true
      
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information (Optional)
      description: Include any other relevant information, context, or references.
    validations:
      required: false
